feat: Add monitoring data gathering
redhat-performance/backstage-performance pull request #14
Opened 2023-11-10 15:34 UTC by jhutar

2023-11-10 15:35 UTC, jhutar commented
/test ?

2023-11-10 15:36 UTC, jhutar commented
/test baseline-pr

2023-11-11 20:52 UTC, jhutar commented
/test baseline-pr

2023-11-13 07:00 UTC, jhutar commented
/test baseline-pr

2023-11-13 08:36 UTC, jhutar commented
/test baseline-pr

2023-11-13 09:17 UTC, droslean commented
/retest

2023-11-13 10:24 UTC, pmacik requested changes
@jhutar Nice, good job!

There are some corner cases that need to be fixed, though - PTAL 
https://github.com/pmacik/backstage-performance/commit/21a5edc8c9a6f5c26d77e9730a91b9c7a7504541

2023-11-13 10:46 UTC, jhutar commented
Thank @pmacik . Cherry-picked your commit.

2023-11-13 11:51 UTC, pmacik commented on ci-scripts/rhdh-setup/deploy.sh
> +        sed -i 's/enableUserWorkload:.*/enableUserWorkload: true/g' config.yaml
```suggestion
        sed -i '/^enableUserWorkload:/d' config.yaml
        echo -e "\nenableUserWorkload: true" >> config.yaml
```

2023-11-13 11:54 UTC, pmacik commented
/test baseline-pr

2023-11-13 12:50 UTC, pmacik commented
/test baseline-pr

2023-11-13 14:55 UTC, pmacik commented
/test baseline-pr

2023-11-13 15:01 UTC, jhutar commented
It worked! But looks like test ends only after `oc logs ...` end :-) Let's try again.

/test baseline-pr

2023-11-13 15:03 UTC, pmacik commented
> It worked! But looks like test ends only after `oc logs ...` end :-) Let's try again.
> 
> /test baseline-pr

yes, my mistake, sorry

2023-11-13 15:17 UTC, pmacik commented
/lgtm

2023-11-13 16:03 UTC, merged

2023-11-14 06:43 UTC, jhutar commented
> > It worked! But looks like test ends only after `oc logs ...` end :-) Let's try again.
> > /test baseline-pr
> 
> yes, my mistake, sorry

Not at all! Thanks for all the fixes!